Task # 38 - Splits introductory vignette into 2.
ITSLeeds/pct pull request #86
Opened 2020-11-28 20:40 UTC by ccamara

As per https://github.com/ITSLeeds/pct/issues/38 request.

2020-11-28 20:59 UTC, Robinlovelace commented
Looks good to me @ccamara, I resolved some conflicts (did you start with the most recent, e.g. recently cloned) version of the repo? If it passes the CI tests above I plan to merge it and add you to as a contributor, if you like (do you have an ORCID ID if so?).

2020-11-28 22:30 UTC, Robinlovelace requested changes
Looks good but tests are not passing for reasons outlined in a comment. Happy to talk over how to best proceed but it may be best starting a new PR based on the latest version of the repo.

2020-11-28 22:30 UTC, Robinlovelace commented on vignettes/reproducing_pct_results.Rmd
> +lwd = wight_lines_30$all / mean(wight_lines_30$all) * 5
The problem here is that the object `wight_lines_30` has not yet been created. I suggest starting from a more recent version of the package (I made a load of changes to the `pct.Rmd` file in the last few days) may be the best way forward.

2020-12-05 11:28 UTC, ccamara commented
Ok, will do it this weekend (as you can see, I'm just doing that on weekends and you may have updated the repo since last time I forked it) with the same date version (probably in another PR, as I don't want to lose time fixing conflicts)!

2020-12-05 13:16 UTC, Robinlovelace commented
Thanks @ccamara if you have any questions on updating it just let me know.

2020-12-06 16:35 UTC, closed without merging