Create Million_KMs-Cycled-Per-Year.rmd
ITSLeeds/pct pull request #94
Opened 2020-12-18 18:18 UTC by natesheehan

- RE issue #59 
- Rough first draft discussing how to calculate, compare and use the PCT models

2020-12-18 21:26 UTC, Robinlovelace commented
Thanks for this @natesheehan. I think there's an issue with vignette titles:

https://github.com/ITSLeeds/pct/runs/1578485229#step:9:151

2020-12-18 21:29 UTC, Robinlovelace requested changes
Looks good, needs a different title for the tests to pass. Also could you rename the file, e.g. from

```
Million_KMs-Cycled-Per-Year.rmd 
```

to

```
km-cycled.Rmd
```

Short and sweet!

2020-12-18 21:29 UTC, Robinlovelace commented on vignettes/Million_KMs-Cycled-Per-Year.rmd
> +  %\VignetteIndexEntry{Reproducing cycling potential estimates in UK cities}
This should be updated to: Estimating million km's cycled per zone in England and Wales regions

2020-12-19 11:24 UTC, natesheehan reviewed
Ah yep sounds good

2020-12-19 15:24 UTC, Robinlovelace commented
Many thanks @natesheehan, looking good. It's still complaining about duplicate title, not 100% sure what it's going on about tbh or how to fix it... 2 options: I merge now and fix up on my branch or you give it another bash. You call!

2020-12-19 18:49 UTC, natesheehan commented
Hm let me try deleting this PR and creating a new one // if not have a go on your branch.

2020-12-19 18:49 UTC, closed without merging