Create km-cycled.Rmd
ITSLeeds/pct pull request #96
Opened 2020-12-19 18:51 UTC by natesheehan

New PR re #59

2020-12-19 20:29 UTC, Robinlovelace requested changes

2020-12-19 20:29 UTC, Robinlovelace commented on vignettes/km-cycled.Rmd
> +  %\VignetteIndexEntry{Reproducing cycling potential estimates in UK cities}
I think... updating this line to say:

```
   %\VignetteIndexEntry{Estimating million km's cycled per zone in England and Wales regions}
```

Will fix the error.

Looking good in any case!

2020-12-21 21:53 UTC, Robinlovelace commented
Many thanks for the update, let's hope it passes the check this time! Good to merge from your perspective @natesheehan ?

2020-12-22 16:28 UTC, natesheehan commented
tests were passing before 🥳  have committed some text edits, happy to merge from my side! 🚲

2020-12-22 17:01 UTC, Robinlovelace commented
> tests were passing before partying_face have committed some text edits, happy to merge from my side! bike

:tada: 

Many thanks for the persistence on this. Looking good, look forward to seeing it on the website!

2020-12-22 17:01 UTC, Robinlovelace approved these changes

2020-12-22 17:02 UTC, merged